### ISSUE TITLE
Possibility to run Deepmass on a local server 

### ISSUE THREAD

**Issue by MarcIsak** [verilylifesciences/deepmass#2]
Hi, 

I wonder there’s a possibility to run Deepmass PRISM locally with TensorFlow and NVIDIA docker for instance? 

Best, 

Marc

**Comment by petercim** [comment]
Hi Marc,

Unfortunately, we currently don't offer a local binary/image yet.

Best,
Peter

**Comment by pgrosu** [comment]
But in the [Nature paper](https://www.nature.com/articles/s41592-019-0427-6) it seems to indicate otherwise:

![deep_mass](https://user-images.githubusercontent.com/6555937/61191483-26940800-a679-11e9-973c-ec7ac2ee5b69.png)

**Comment by MarcIsak** [comment]
Yes, the paper indicates that one could get a local version of Deepmass. I will spend some time in China so using Google services overall is a ‘no no’ over here...

I am looking forward to try that local version :). 

Best, 

Marc
