### ISSUE TITLE
Prediction of iRTs

### ISSUE THREAD

**Issue by MarcIsak** [verilylifesciences/deepmass#3]
Hi, 

is there a plan to include indexed retention time(iRT) prediction in Deepmass PRISM? When building a spectral library for SWATH/DIA, you would normally include iRT values to get higher confidence in the spectral matching. 

Best, 

Marc

**Comment by petercim** [comment]
Hi Marc,

We are planning on offering our iRT model as well, but it may take some time before we set it up.

Best,
Peter
