### ISSUE TITLE
Is this project still alive

### ISSUE THREAD

**Issue by joydisette** [verilylifesciences/deepmass#5]
My understanding is that DeepMass is a service on GCP yet cannot find it anywhere. Is this still supported?

**Comment by petercim** [comment]
Hi Houda,

Thanks for your interest in using DeepMass! Yes, DeepMass:Prism model is still available via GCP ML Engine/AI platform, and can be used as described here: https://github.com/verilylifesciences/deepmass/tree/master/prism . Don't hesitate to let us know if you have any further questions.

Best,
Peter
