### ISSUE TITLE
error

### ISSUE THREAD

**Issue by naomikk7** [verilylifesciences/deepmass#6]
Hi,
I tried batch mode several times but it gave me error message like this: 

ERROR: (gcloud.ml-engine.jobs.submit.prediction) Projects instance [angular-stacker-325501] not found: Field: prediction_input.model_name Error: The model resource: "deepmass_prism" was not found. Please create the model resource first by using 'gcloud ai-platform models create deepmass_prism'.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: "The model resource: \"deepmass_prism\" was not found. Please create\
      \ the model resource first by using 'gcloud ai-platform models create deepmass_prism'."
    field: prediction_input.model_name
 
Can you pls help me with it? Thank you!

**Comment by snail123815** [comment]
Same here, didn't get any reply from the email address listed. Cox only told me that I should do as the git readme.

**Comment by pgrosu** [comment]
@naomikk7 and @snail123815 Just out of curiosity I tried to list the models available, and there are none available to perform any AI prediction.  For example:

```Bash
[pgrosu]$ gcloud ml-engine models list
Listed 0 items.
[pgrosu]$
```

Maybe they are still in the process of updating Google's AI model resources.  It mentions that contacting [DeepMass@google.com](DeepMass@google.com.) might help.

**Comment by snail123815** [comment]
@pgrosu I have contacted them for quite some times already, no reply from that side.

The empty list I think is actually because updated google policy, they do not expose existing models to users like before I guess. But I don't know how to find and add the deep mass model.

**Comment by pgrosu** [comment]
@snail123815 I wouldn't be surprised if DeepMass might be a [Google dead project](https://killedbygoogle.com/), and we just weren't told about it, see: https://killedbygoogle.com/

**Comment by petercim** [comment]
Hi all,

First, apologies for the slow reply. The DeepMass project isn't a dead Google project, but we have been either away or distracted by other work.

Re: this issue -- I'm still looking into it. It seems there's been a change in project region. Could someone here try selecting `global` instead of `us-central1` region, and see if that makes any difference?

**Comment by snail123815** [comment]
Hi @petercim,
Thanks for clarifying! This worked:
```sh
gcloud ai-platform predict --model deepmass_prism --project deepmass-204419 --format json --json-instances "input.json" --region global > prediction.results
```

**Comment by petercim** [comment]
Glad to hear that worked, thanks for giving it a try @snail123815 ! I just updated the README file and will now close this issue. Thanks all!
