### ISSUE TITLE
Can't find Google Group

### ISSUE THREAD

**Issue by EvelinaPillai** [verilylifesciences/deepmass#8]
Hi,

Sorry for posting here but I wanted to reach out on your Google Group, unfortunately I can't find any Google Group under "DeepMass@google.com"

Can you help me out ?

Best regards,
Evelina

**Comment by petercim** [comment]
Hi Evelina,

Sure, how can I help?

Best,
Peter

**Comment by EvelinaPillai** [comment]
Hi Peter, 

We would like to apply the in-silico predicted spectral library from Prism to increase the number of protein IDs and improve protein quantification (LFQ) of a DDA experiment.

In this context, we would like to ask the following question:

Can Prism be implemented in a standard MaxQuant workflow for LFQ?  
Maybe in a way that the predicted intensities from the output of Prism can be imported into MaxQuant to improve the peptide identification and therefore also LFQ of proteins?

We would be very grateful for your support. Thank you very much in advance!


Best regards,
Evelina

**Comment by petercim** [comment]
Hi Evelina,

I suggest you reach out to Prof. Juergen Cox, who has been integrating
Prism into MaxQuant.

Best,
Peter
